# Dockerfile.bot
FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt /app/requirements.txt

# Install system dependencies and Python packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

# Copy bot code
COPY nmadur_bot /app/nmadur_bot

ENV PYTHONUNBUFFERED=1

# Start bot
CMD ["python", "nmadur_bot/main.py"]
